# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcJaBS3wOwcSNak4CaO2Iy_DZ9JVhpIY
"""

!pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# URL of the webpage
URL = "https://medlineplus.gov/endometriosis.html"

# Send request to website
try:
    response = requests.get(URL)
    response.raise_for_status()  # handles HTTP errors
except requests.exceptions.RequestException as e:
    print(f"Error fetching the page: {e}")
    exit()

# Pause to follow ethical scraping practices
time.sleep(1)

# Parse HTML content
soup = BeautifulSoup(response.text, "html.parser")

# List to store extracted data
data = []

# Find all section headings (categories)
sections = soup.find_all("h3")

# Loop through each section
for section in sections:
    category = section.get_text(strip=True)

    # Find the next unordered list under the section
    ul = section.find_next_sibling("ul")

    # Check if list exists (avoids errors)
    if ul:
        items = ul.find_all("li")

        for item in items:
            text = item.get_text(strip=True)

            # Clean text (extra safety)
            if text:
                data.append({
                    "Category": category,
                    "Information": text
                })

# Convert data into DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("data.csv", index=False, encoding="utf-8")

print("Data successfully scraped and saved to data.csv")

from google.colab import files
files.download('data.csv')